package com.ombdev.inventorysystemapi.model;

public enum SortBy {
    ID_DESC,
    CATEGORY_CODE_ASC,
    CATEGORY_CODE_DESC,
    CATEGORY_NAME_ASC,
    CATEGORY_NAME_DESC,

    PRODUCT_NAME_ASC,
    PRODUCT_NAME_DESC,
    PRODUCT_CODE_ASC,
    PRODUCT_CODE_DESC,
    PRODUCT_PRICE_ASC,
    PRODUCT_PRICE_DESC,
    PRODUCT_QUANTITY_ASC,
    PRODUCT_QUANTITY_DESC,

    USER_FULL_NAME_ASC,
    USER_FULL_NAME_DESC,
    USER_USERNAME_ASC,
    USER_USERNAME_DESC,
    USER_EMAIL_ASC,
    USER_EMAIL_DESC,
    USER_PHONE_ASC,
    USER_PHONE_DESC,

    CUSTOMER_CODE_ASC,
    CUSTOMER_CODE_DESC,
    CUSTOMER_FULL_NAME_ASC,
    CUSTOMER_FULL_NAME_DESC,
    CUSTOMER_PHONE_ASC,
    CUSTOMER_PHONE_DESC,
    CUSTOMER_EMAIL_ASC,
    CUSTOMER_EMAIL_DESC


}
